### ISSUE TITLE
Add extra check to dead peer removal, that pings the proposed dead peer to verify a timeout. In the case that the node actually isn't down, create an Observation for "IncorrectDeadPeerNotice".

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1070]

**Comment by marcinwadon** [comment]
@buckysballs This can lead to forks because some nodes will remove the dead peer and some no.
I'd say that apart from that, we have to determine a way to work with the nodes which can have no connection between each other. If it's not possible, we have to keep consistency along all the peers. Maybe each join or drop can be under the consensus? Just thinking loudly

**Comment by marcinwadon** [comment]
- [ ] Add additional check if node will receive dead peer notice from others
- [ ] Create an observation "IncorrectDeadPeerNotice" if dead peer isn't dead

**Comment by marcinwadon** [comment]
we’ll make the request to the dead peer with a very small timeout, and then a final n^2 blast (note this can use gossip later on) of a “decision” of whether or not to remove the node. The flow will be a typical “gather apply scatter” like consensus

- node times out on dead peer
- node sends alert to other peers
- peers make super short ping
- peers share the responses of their pings, based on responses all nodes remove or keep slow peer
(node knows how many nodes are in the cluster so once node will get all responses from the nodes (cluster size - 2 (own and dead peer)), node can decide)
