### ISSUE TITLE
Verify double spent protection

### ISSUE THREAD

**Issue by ThomasvandenBroek** [Constellation-Labs/constellation#1216]

**Comment by marcinwadon** [comment]
And what about blacklisting?

**Comment by TheMMaciek** [comment]
I have found three places where we are verifying/checking transactions:

1. When submitting a new transaction through POST on `/transaction`
2. When pulling transactions for consensus from pending transactions mempool
3. When accepting a checkpoint block

**Ad. 1)** We are doing some sanity checks on lastTransactionRef:
- if it's the same throughout the body of the request
- if `lastTxRef`'s hash is not empty for `ordinal > 0`
- if `lastTxRef`'s ordinal is greater then last accepted tx, or when it's equal if the hashes are the same

So theses checks should prevent double spend transactions if we already got the previous transaction processed and accepted. Because we are processing transactions on many nodes we can't verify more at this step I think.

**Ad. 2)** We are currently pulling all transactions for a given address that have ordinal for `lastTxRef >= lastAcceptedTransaction.ordinal` and which sorted by `ordinal` have
a transaction referencing `lastAcceptedTransaction` as a first transaction.
We are not checking if all transactions for a given address that we are about to pull form a correct chain so we can have a chain right now of `tx1`, `tx2`, `tx10` and it would be pulled for consensus.
We can improve that and pull only consecutive correct chain of transactions.
This improvement is in progress in #1241.
Without it we could possibly accept a transaction of an arbitrary ordinal and then block pulling missing transactions because of accepting this transaction as lastAcceptedTransaction during checkpoint block acceptance.

**Ad. 3)** First we are checking if transactions in a checkpoint block for a given address sorted by `ordinal` have the first transaction correctly referencing `lastAcceptedTransaction`.
If that's not the case the checkpoint block cannot be accepted yet and we are starting the resolving for missing transactions.
If there is no problem with `lastAcceptedTransaction` then during the process of accepting the block we are:
- checking if `lastAcceptedTransaction` for given address has `ordinal >=` than transaction being accepted, if yes that's a double spend (but I guess this case is ruled out when checking missing transaction references)
- checking if transactions being accepted don't have repeated ordinals for a given address, if yes that's a double spend

Next we are adding addresses that performed double spend to a `blacklist` (that blacklist will be checked during pulling blocks from awaiting pool if there are any. And if there is a block with transaction from blacklisted address then this block will not be passed to a recursive call of accept method - this check is only performed for a recursive call of accept method).
Then filtering out the double spend transactions and accepting all other transactions.
And then transfering the funds between addresses and checking blacklisted addresses while doing that, so if an address was marked as blackilsted because of having double spend transactions earlier, the funds will not be transfered even for not double spend transactions (but these transactions will be accepted in a previous step).

Summarizing I think we have good protection against double spend altogether.
I'm not sure though about the process of pulling and accepting transactions.
I think we should:
- pull only correct transaction chain for consensus, that's being implemented in #1241
- after that the transactions in a checkpoint blocks should form a correct chain, but maybe we should also recheck that chain while accepting a block
- also I noticed that we are not accepting transactions from a checkpoint block in some particular order (no sorting) and if I'm not mistaken that can mean that while accepting a checkpoint block we accept `tx5` after `tx10` and hence `lastAcceptedTransaction` will be `tx5` - we don't accept transactions for a given address while enforcing order
- the blacklist of addresses is being cleared only when node is joining - the question is if that's not too restrictive, as that can mean (if I got it right) that after one double spend incident no funds can be ever transferred from a given address 

Can you guys @marcinwadon, @buckysballs check if my observations are right or if I missed something and if we need to take some actions?

**Comment by marcinwadon** [comment]
> after that the transactions in a checkpoint blocks should form a correct chain, but maybe we should also recheck that chain while accepting a block

I think it's a good point to reverify it in the checkpoint block acceptance :+1:

> also I noticed that we are not accepting transactions from a checkpoint block in some particular order (no sorting) and if I'm not mistaken that can mean that while accepting a checkpoint block we accept tx5 after tx10 and hence lastAcceptedTransaction will be tx5 - we don't accept transactions for a given address while enforcing order

let's double check it and if so, this must be fixed

> the blacklist of addresses is being cleared only when node is joining - the question is if that's not too restrictive, as that can mean (if I got it right) that after one double spend incident no funds can be ever transferred from a given address

we need to ask Wyatt or Mathias for that. My question would be what if we're discovering double spend attempt - right now we're doing nothing. Should we i.e. add metrics and/or store those addresses, so after few attemps blocking it as well?

**Comment by TheMMaciek** [comment]
Additionally we could address two more cases:
- The `PendingTransactionsMemPool` can grow infinitely, we are not removing old transactions from pending. When we start to enforce the chain to be correct we may have e.g. transactions with incorrect hashes for lastTxRef and they may get stuck in pending forever. We could implement caching and remove transactions that are stuck in pending, or catch errors upon validation and persist/accept these transactions as invalid, or just remove them.
- We are checking `blacklist` in two places: 1. when filtering blocks awaiting acceptance, 2. when transferring the funds. We could check `blacklist` when transaction is being submitted to not allow such transactions in.
