### ISSUE TITLE
Clean up wiki and repo docs

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#136]
Fill out the wiki page

**Comment by Nikolaj-K** [comment]
There's a PR with a /docs folder in the constellation and I propose an approach that uses cross-linking over duplication of text (because duplication makes maintainance harder and leads to outdated text snipets). 

Regarding the repositories, there were some renamings introducing a convention last month, but they have since again been broken. In particular, there's now 3 different repositories that have the following names:

* whitepaper
* whitepaper_v1
* whitepaper-1.0

The first is the (rather outdated and more or less) technical whitepaper from 2017. The second is the new business whitepaper (which however has some broadly painted technical parts too, if you will). 

As opposed to the research paper repositories (the two which are public are hylochain and proof-of-meme), the public whitepapers don't hold the .tex files, which disables typo correction. 

I propose to stick to a lower letter and dash convention, before people see no red thread and re-add files without coherent namings. I think the best here would be to take the `whitepaper` repo and add two subfolders

whitepaper/technical-whitepaper

whitepaper/business-whitepaper

(and in whitepaper/README.md a link to the pdfs, which are contained in those repspective folders, and a short note on context/history of them, etc.)

The other option would be to have two repos for those two, and call them, respectively

whitepaper-technical

whitepaper-business

In any case, the third (private) repo should be renamed to something like

whitepaper-working-files

The files corrently holding .tex have tmp and auxiliary files, and I recommend including the .ignore file linked below

https://github.com/Nikolaj-K/NOS-voting-system-research/blob/master/.gitignore
