### ISSUE TITLE
Prioritize peer health check endpoint by specifying thread pool

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1377]
We've noticed inconsistencies in peerList across nodes that correspond to redownload loops. Currently out api operates off of the unbounded thread pool, but we shold be able to specify one of our other pools to ContextShift, effectively prioritizing a call to the /peerHealth endpoint over others. 

DoD)

- Change thread pool used in /peerHealth 
- Unit test with hanging call on /reDownload endpoint followed by successful call to /peerHealth

**Comment by marcinwadon** [comment]
@buckysballs Is it confirmed that the issue is because of the thread pool? I believe that thread pool has nothing to do here, API call is on separate pool so it will not hang. Calls to health endpoint are being made in separate process so it does not hang any other process, yet it's on own thread pool as it is a scheduler. If it jumps to the wrong thread pool, I'd say we should remove an existing shift, not add one another.
