### ISSUE TITLE
Snapshot health check and re-download

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#220]
Nodes should periodically (ideally during health check) request the last 10 snapshot hashes from other peers and check against their own. If they've entered a corrupted state (i.e. no alignment with majority of other peers,) they should attempt to re-download and correct themselves to be aligned with majority.

**Comment by ryle-goehausen** [comment]
Corruption state should potentially be a separate ticket? Unsure

**Comment by buckysballs** [comment]
Nodes need a process that checks if the've become unhealthy or out of sync with the rest of the cluster. The simplest case we begin with is checking for inconsistent data across peers. We can check consistency across nodes with snapshots as they are a deterministic process based on the total set of checkpoint blocks a node has received. Given that snapshots occur in pairs, each node should check at the creation of every 4 snapshots if its last two snapshots are out of sync. If they are, we need to accept one of potentially many snapshots across peers according to deterministic logic and download the missing data (transactions). Eventually we will want to define deterministic logic based upon our reputation system #361, but for determinism is all we need for success criteria. Inconsistency really shouldn't happen in a could environment so we should make sure that's solved before addressing this issue.

We will want to add more checks beyond inconsistency such as health checks so we should follow the Periodic pattern, and to start, implement the above.

**Comment by buckysballs** [comment]
Based on our last cluster test with concurrent consensus we ran into what looks like a timing edge case around nodes accepting a checkpoint from a consensus round that it did not participate in, due to it not being accepted in time for snapshot creation. This could always be a possibility due to clock synchronization, or network delays. To counteract this, a lets create a periodic health check with 1.5x the interval as snapshot creation, which checks the 6 most recent shapshot hashes. In the case of misalignment, lets choose the most common with a tie break by sorting the hashes (groupby(_._1).reduceByKey (_+_).sortBy(_._1)). This will be replaced by incorporating reputation info, but for now we just need a deterministic process for validity.

Specifically lets:
1) Create a Periodic process for querying the most recent 6 snapshots (current and 5 previous) across all nodes.
2) Implement the deterministic process above ^ for choosing hashes in case of misalignment
3) In the case that the checkpoint is missing, download the data from peers, accept, then store
4) Migrate checkpoint blocks back into the mempool if they are in a misaligned snapshot and not the accepted snapshot, so they will be available for the next snapshot creation

Notes:
1) We should try different time intervals and number of snapshots
