### ISSUE TITLE
Safe updates for account balances / ledger / child/ancestry relations

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#225]
See example here: https://github.com/rchain/rchain/blob/d42f71d78637fa0385fc9139bb41480d3efb4d45/rspace/src/main/scala/coop/rchain/rspace/concurrent/MultiLock.scala#L11
^ Above code can be used with appropriate citation in header.

Transaction balance updates need to lock both addresses when performing an update. The current balance application function is thread safe only because the updates are locking the entire class. https://github.com/Constellation-Labs/constellation/blob/696e6d6ee6ad30fe9e41b2d2d78bb0b52bb35bd5/src/main/scala/org/constellation/primitives/Schema.scala#L226

Address service should instead be backed by a TrieMap of AddressCacheData and access granted through a TrieMap semaphore. CheckpointCacheData should also be backed by a similar mechanism, except with locks applying to parent / child relationship updates.

Should also optionally include a separate TTL structure for removing old keys from semaphore storage.

**Comment by Nikolaj-K** [comment]
Is the header remark one about license? I see the RChain repo has a short Apache2 one and Constellation does too, but I don't know to what extent those were choosen consciously (rather than Apache sounding familiar because it's a well known provider of software in your space). The MIT one is really far more common in crypto projects. I had questions about the reasoning behind the open source license to Wyatt at one point but he didn't make a distinction. Maybe it's worth out brainstorming over why this-or-that choice is adopted or what the goals are. Apache means people using the code do have to do more cleanups, annotate and add/remove names of the source, formal handling of intellectual and I don't know if there is overhead for people building on the protocol when you mix MIT tools with Apache.
