### ISSUE TITLE
Transaction gossiping prototype

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#228]
When a node generates a new transaction, it should broadcast it to a random subset of peers. This will change upon implementation of partitioning scheme.

Nodes receiving this transaction should not yet store it in their mem pool (otherwise we'll create duplicates unnecessary until partitioning and consensus upgrades are finished.) They should store it in the transaction service and then (if this is the first time they've observed it,) they should gossip to it to another random fraction of their peers.

This doesn't need to influence the current E2E operations yet, but only needs to be implemented and tracked with metrics for purposes of load testing gossip. It will later be used more.

Need to make sure data does not pose a risk of crashing the nodes. Ideally unused transactions need to be cleaned up regularly. See also ticket about auxiliary DB storages for block explorer stuff.

**Comment by Nikolaj-K** [comment]
This just as a remark to the use of "random" here and also relates to "Control key and node update mechanism": If people are under the impression they could get better reputation/rewards from choosing their communication implementation strategically, then they will be way of updates that are more or a proposal, let alone people being conservative of rewrites on the security block of the code. 

That's not as relevant for the testnet testing champagnes, but I'm wary of restricting practices (hacks for a smoother work flows) where eventually there ends up being fatigue to refactor it away again. 
Not sure about the plan exactly here though, and how this caution applies. Worth looking at projects like Monero which afaik routinely do sort forks that are smoothly adopted by all the relevant node hosters.

**Comment by ryle-goehausen** [comment]
Partially implemented but not complete. Its transmitting data but not using it yet or rebroadcasting with a falloff.

**Comment by wkoszycki** [comment]
>Ideally unused transactions need to be cleaned up regularly

Under what condition node should move (or remove ?) transaction from service  ?

**Comment by ThomasvandenBroek** [comment]
Estimate: 3 days

**Comment by buckysballs** [comment]
The complexity of broadcasting transactions in our current, send to all approach, will be an n^2 operation. As our cluster grows in size, this will become a performance bottleneck. In order to scale our cluster we will want to adopt a scalable broadcasting method to reduce complexity and prevent bottlenecks. A method that can achieve this is a gossip protocol. There are many implementations of a gossip protocol, but for our first implementation we can use a use the following approach, ignoring XOR/kademlia distance which will eventually be required for light nodes, but is conceptually much simpler.

We can define a formula for the number of times a transaction needs to be sent random peer in order for that transaction to be propagated to all peers as

log~FAN_OUT~(TOTAL_PEERS)

where FAN_OUT = mod~10~(TOTAL_PEERS)+1

1) Add a `path: Seq[ID]` field to transactions, for adding keeping track of the path each transaction follows when being spread through the cluster.
2) When a transaction is received, if we have not seen it before, and the length of the `path` field is <= FAN_OUT, randomly select the diff of all peer IDs and all Peers in the `path` field and send to that peer

The following resource is really helpful at demonstrating this effect
https://flopezluis.github.io/gossip-simulator/
