### ISSUE TITLE
Main Net Swap - dry run

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#396]
For our main net swap we will want to 'freeze' our erc20 state at a given Ethereum block number and use that state to start a cluster with balances of that state. 

1) Hard code token allocations from our erc20 smart contract to the genesis block of a cluster. Ensure balances are correct.

2) Ensure that public/private key pairs from the erc20 token are still valid to send/recieve $dag and that a peer associated with it can join/leave.

**Comment by Nikolaj-K** [comment]
Given that the priv->pub->addr calculation on Ethereum is different than on Constellation currently (e.g. the former iirc involving a keccak hash of the public key), will the approach be to have users figure out their public key (might require an offline app/script) and then get assigned a new address based on it (with the hash and scheme that the DAG uses)? 

Does the priv->pub already correspond 1:1 with Ethereum (I think the curve is the same, so that answer might be yes)? Or does this cluster have new implementation that then work with the rest of the network?

I remember there was some registering of address involved on EOS, which I suppose was a little more inconvenient for the users. It would indeed be cool and less error prone if such a thing is not necessary and the private keys stayed the same as you seem to propose here - I was just unsure if the Constellation setup is close enough to Etheruem.
