### ISSUE TITLE
Provide KeyPair for creating Genesis externally

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#709]
Currently the `CoinBase` keypair is randomly generated. We need to provide it externally, so Genesis creator can use his wallet to send initial transactions. This is the keypair used for creating Genesis and initial distribution.

**Comment by kpudlik** [comment]
@buckysballs so basically we have there same issue as with the Stardust.

Currently we just have `private val CoinbaseKey = KeyUtil.generateRandomKeyPair` but we should probably provide the "incorrect" keypair externally or sth.

**Comment by buckysballs** [comment]
Just went over the next cohort of tix and we can simplify this by just supplying a keypair that's specified as the "genesis keypair" during application start. So we can basically reuse the same flow as for #638 to load the keypair, but we should have a hard coded path into resources or /tmp where the genesis keypair should be stored. Given that we don't need to make this configurable for state channels, we can store the genesis keypair in that path by default. 

In order to validate the genesis block, we can reload the starting csv with prev account balances from the erc20 ledger, and verify that a payload of the csv starting balance transactions with the genesis keypair is the genesis hash.
