### ISSUE TITLE
Modify Edge for BOLOS app

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#735]
We'll need to modify the payload of Edge to allow compatibility with our Nano Ledger app. We'll need to a run length encoded array as opposed to json.

I.E. instead of:

{"parents": ["a","b1"], "amount": "c12", "salt":"d123"}

pass in:

21a2b23c124s123

which is

(number of parents) 2

(length of parent 0) 1

(value of parent 0) "a"

(length of parent 1) 2
(value of parent 1) "b1"

(length of amount) 3
(value of amount) "c12"

(length of salt) 4
(value of salt) "d123"

DoD) 
1) Modify current Edge structure to sign on the payload above

**Comment by buckysballs** [comment]
Looks like I left some off here, we need to run length encode all members of TransactionEdgeData and LastTransactionRef as well. The full breakdown for encoding is as follows:

instead of:

{"parents": ["a","b1"], "amount": "c12", "salt":"d123"}

pass in:

21a2b23c124s123

which is

(number of parents) 2

(length of parent 0) 1

(value of parent 0) "a"

(length of parent 1) 2
(value of parent 1) "b1"

(length of amount) 3
(value of amount) "c12"

(last tx ref length) _
(last tx ref) _

(last tx ref ordinal) _
(last tx ordinal) _

(length of fee) _
(value of fee) _

(length of salt) 4
(value of salt) "d123"

**Comment by coranos** [comment]
cool, I will update the code (hopefully tonight)
I'm assuming the following:
- last tx ref should be displayed as hex.
- last tx ordinal should be displayed as base-10.
- fee should be displayed as base-10.
- salt should be displayed as hex.

**Comment by buckysballs** [comment]
Hey @coranos! I just finished the last changes conforming our signature payload to the one above. Note, I assumed that you require amount in hexString as well based on your description. Here's a run length encoded transaction:

`240DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj3440DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj3475f5e10018LastTransactionRef101016cfa3b426875ce3d9`

reformatted (just for clarity here):

`2 
 40 
 DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34 
 40 
 DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34 
 7 
 5f5e100 
 18 
 LastTransactionRef 
 1 
 0 
 1 
 0 
 16 
 b3f92043b0db5933`

Of the following transaction:

`{"edge":{"observationEdge":{"parents":[{"hashReference":"DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34","hashType":"AddressHash","baseHash":null},{"hashReference":"DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34","hashType":"AddressHash","baseHash":null}],"data":{"hashReference":"75f5e10018LastTransactionRef10101666498342c91b1383","hashType":"TransactionDataHash","baseHash":null}},"signedObservationEdge":{"signatureBatch":{"hash":"da748ee6a2e89f1884b3fb7b9fd8511b0ce68f27086922399f9a186a49a9cb41","signatures":[{"signature":"304502205b7295edcbf137240ee6ac6b4a85b1cc6a8738c8ca6c4398b4106222947f16a0022100bb2b88a6d44c5f5a310d214f1c2020f399068d7f4d5a291cf240dc9ee4366856","id":{"hex":"ebb7c26c168731b29c769138c042feb6793d835e8183513e043018451464a0c06f8531093d25e086251b3fc1051b90148fb2fe2acd0845e695da87588344bef8"}}]}},"data":{"amount":100000000,"lastTxRef":{"prevHash":"LastTransactionRef","ordinal":0},"fee":null,"salt":7370566588033602435}},"lastTxRef":{"prevHash":"","ordinal":0},"isDummy":false,"isTest":false}`

If that all looks good to you, then when #1076 is merged and deployed, you're ready to test on the cluster 💪

**Comment by coranos** [comment]
Nice. Is there a UI I can use to create an account and get some coins to test with? I see the amount is 100000000, fee 0, so whatever amount would be good to test with.

or if validator nodes are available, I can just set up my validator node and use the coins I get from that to test the ledger app.

**Comment by buckysballs** [comment]
So the easiest way would be to make a keypair and then post your kp's address in Gitter https://gitter.im/constellation-operators/community and any node operator in the test net can send you some $dag. Those changes are getting deployed rn, so you can hop in whenever 💪

**Comment by coranos** [comment]
Ok I finally had time to take a look. 

I have some bugs to fix on my side with the display, but the encoded tx isn't quite right either.

hex encoding isn't right. "hex encoding" is base16. the string "DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34" is base58.

in addition the prevHash is set to "LastTransactionRef" which is not base16 either.

an example of a base16 hash is da748ee6a2e89f1884b3fb7b9fd8511b0ce68f27086922399f9a186a49a9cb41. notice that everything is base-16. 0,1,2,3,4,5,6,7,8,9,0,A,B,C.

so the correct encoded tx is:
```

let encoded = '';

// (number of parents, in bytes, in hex)
encoded += '02';

// (length of parent 0 in bytes, in hex)
encoded += '1E';

// (value of parent 0, in hex) DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34
encoded += '010BD9EC9606EB840875043E6DBAD8625197D6335BB690070E1E83B5ACAF';

// (length of parent 1 in bytes, in hex) DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34
encoded += '1E';

// (value of parent 1)
encoded += '010BD9EC9606EB840875043E6DBAD8625197D6335BB690070E1E83B5ACAF';

// (length of amount in bytes)
encoded += '04';

// (value of amount, in hex)
encoded += '05F5E100';

// (last tx ref length in bytes)
encoded += '20';

// (last tx ref, in hex)
encoded += '0000000000000000000000000000000000000000000000000000000000000000';

// (length of last tx ref ordinal, in hex)
encoded += '01';

// (last tx ordinal, in hex)
encoded += '00';

// (length of fee, in hex)
encoded += '01';

// (value of fee, in hex)
encoded += '00';

// (length of salt, in hex)
encoded += '08';

// (value of salt)
encoded += '66498342C91B1383';
```

```
021E010BD9EC9606EB840875043E6DBAD8625197D6335BB690070E1E83B5ACAF1E010BD9EC9606EB840875043E6DBAD8625197D6335BB690070E1E83B5ACAF0405F5E100200000000000000000000000000000000000000000000000000000000000000000010001000866498342C91B1383
```

for the following transaction:
```
{
  "edge": {
    "observationEdge": {
      "parents": [{
        "hashReference": "DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34",
        "hashType": "AddressHash",
        "baseHash": null
      }, {
        "hashReference": "DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34",
        "hashType": "AddressHash",
        "baseHash": null
      }],
      "data": {
        "hashReference": "75f5e10018LastTransactionRef10101666498342c91b1383",
        "hashType": "TransactionDataHash",
        "baseHash": null
      }
    },
    "signedObservationEdge": {
      "signatureBatch": {
        "hash": "da748ee6a2e89f1884b3fb7b9fd8511b0ce68f27086922399f9a186a49a9cb41",
        "signatures": [{
          "signature": "304502205b7295edcbf137240ee6ac6b4a85b1cc6a8738c8ca6c4398b4106222947f16a0022100bb2b88a6d44c5f5a310d214f1c2020f399068d7f4d5a291cf240dc9ee4366856",
          "id": {
            "hex": "ebb7c26c168731b29c769138c042feb6793d835e8183513e043018451464a0c06f8531093d25e086251b3fc1051b90148fb2fe2acd0845e695da87588344bef8"
          }
        }]
      }
    },
    "data": {
      "amount": 100000000,
      "lastTxRef": {
        "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
        "ordinal": 0
      },
      "fee": 0,
      "salt": "7370566588033602435"
    }
  },
  "lastTxRef": {
    "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "ordinal": 0
  },
  "isDummy": false,
  "isTest": false
}
```

**Comment by TheMMaciek** [comment]
**To clarify about the raw data types before any conversion:**

parents - String, base58
amount - Long, so base10
LastTransactionRef.prevHash - String, base16
LastTransactionRef.ordinal - Long, so base10
fee - Long, so base10
salt - Long, so base10

And for a more representative transaction example:
parents = ["DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34", 
                  "DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj56"]
amount = 100000000
prevHash = "08e6f0c3d65ed0b393604ffe282374bf501956ba447bc1c5ac49bcd2e8cc44fd"
ordinal = 567
fee = 123456
salt = 7370566588033602435

(@coranos can you have a look and check if the description of the format and actual values below for the given transaction are what you need? Just so that we are on the same site.)

the encoding:

`let encoded = '';

// (number of parents, in hex)
encoded += '02';

// (length of parent 0 in bytes, in hex) - 40 chars in base58 == 30 in bytes
encoded += '1E';

// (value of parent 0, in hex) - DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34
encoded += '010bd9ec9606eb840875043e6dbad8625197d6335bb690070e1e83b5acaf';

// (length of parent 1 in bytes, in hex)
encoded += '1E';

// (value of parent 1) - DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj56
encoded += '010bd9ec9606eb840875043e6dbad8625197d6335bb690070e1e83b5ad25';

// (length of amount in bytes, in hex)
encoded += '04';

// (value of amount, in hex)
encoded += '05F5E100';

// (last tx ref length in bytes, in hex)
encoded += '20';

// (last tx ref, in hex)
encoded += '08e6f0c3d65ed0b393604ffe282374bf501956ba447bc1c5ac49bcd2e8cc44fd';

// (length of last tx ref ordinal in bytes, in hex)
encoded += '02';

// (last tx ordinal, in hex)
encoded += '0237';

// (length of fee in bytes, in hex)
encoded += '03';

// (value of fee, in hex)
encoded += '01E240';

// (length of salt in bytes, in hex)
encoded += '08';

// (value of salt in hex)
encoded += '66498342C91B1383';`

`021E010bd9ec9606eb840875043e6dbad8625197d6335bb690070e1e83b5acaf1E010bd9ec9606eb840875043e6dbad8625197d6335bb690070e1e83b5ad250405F5E1002008e6f0c3d65ed0b393604ffe282374bf501956ba447bc1c5ac49bcd2e8cc44fd0202370301E2400866498342C91B1383`

**Comment by TheMMaciek** [comment]
Hey @coranos can you have a look at the comment above and confirm if it's what you need? :)

**Comment by coranos** [comment]
Looks fine to me, yes. I'm looking forward to trying it on testnet.

**Comment by TheMMaciek** [comment]
Cool, there was some ambiguity for me regarding length "in hex"/"in bytes, in hex", the example above always gives length in bytes in hex and that's how it will be implemented :). Ok will let you @coranos know when it's ok to test it on testnet.

**Comment by TheMMaciek** [comment]
Hey @coranos unfortunately address turns out not to be base58 - there are corner cases where we have 0 and " " in the address (not base64 also because of that whitespace). So I guess the best we can do is to treat address as UTF-8.

therefore addresses would be encoded as:
```
let encoded = '';

// (number of parents, in hex)
encoded += '02';

// (length of parent 0 in bytes, in hex)
encoded += '28';

// (value of parent 0, in hex) - DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34
encoded += '44414734386e6d7867704b685a7a457a7963383679396f486f7478784735374738734242776a3334';

// (length of parent 1 in bytes, in hex)
encoded += '28';

// (value of parent 1) - DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj56
encoded += '44414734386e6d7867704b685a7a457a7963383679396f486f7478784735374738734242776a3536';
```

would that be ok?
By the way what's you nick on discord? :)

**Comment by coranos** [comment]
I'm "nano ledger app" on your discord.

You have ... spaces ... in your address?

Can you please share the algorithm you use to convert the public key to the address. The ledger isn't just for signing transactions, it also needs to display the public key for it's private key.

If DAG48nmxgpKhZzEzyc86y9oHotxxG57G8sBBwj34 isn't the simple base58 encoded public key, then the address won't match the private key, and you won't be able to send any funds.

**Comment by TheMMaciek** [comment]
We have one corner case where we use hardcoded string with spaces as address, when the genesis block is being created - check line 19 here:
https://github.com/Constellation-Labs/constellation/blob/dev/src/main/scala/org/constellation/primitives/Genesis.scala

The algorithm generating address may have 0 as the fourth character - check line 227, here:
https://github.com/Constellation-Labs/constellation/blob/dev/keytool/src/main/scala/org/constellation/keytool/KeyUtils.scala

So no we are not using spaces in our addresses in the outside world. But apart from base58 characters we may have 0 (zero). It could be base64, but because of the case above I need to encode it as UTF-8.

**Comment by coranos** [comment]
Ok, looks like I merged several issues. 
- The ledger app only has 1024 bytes ram, so a 555 character string may be a problem. But we'll deal with that later. (It actually has 2000 bytes, but you need half to store the real tx and half to display the tx)
- since spaces and zeroes need to be supported, I'd recommend hex encoded ASCII rather than UTF-8 as it's one byte per character.
- I see your algorithm is 'DAG'+[0-9]+base58. This is great, because I already have a base58 algorithm, so generating the correct address for the private key should work.

**Comment by TheMMaciek** [comment]
Yeah the address is as you described: 'DAG'+[0-9]+(36 base58 chars).
Actually UTF-8 will generate exactly the same (and equally long) representation as ASCII, as it's "backward compatible" with ASCII.
But I guess we can use ASCII :).

**Comment by TheMMaciek** [comment]
@coranos we also decided that lastTransactionRef.prevHash will be hex encoded ASCII

so:
```
// (last tx ref length in bytes, in hex)
encoded += '40';

// (last tx ref, in hex)
encoded += '30386536663063336436356564306233393336303466666532383233373462663530313935366261343437626331633561633439626364326538636334346664';
```

**Comment by buckysballs** [comment]
@ffox77
