### ISSUE TITLE
Run manual test scenario

### ISSUE THREAD

**Issue by ThomasvandenBroek** [Constellation-Labs/constellation#763]
This ticket has 2 DoD. One for running the simple transaction flow, and one for restoring a node from a backup. 
Before we want to run the long running integration tests we want to make sure that the transaction flow is working correctly.
This goes the same for a node. We want to make sure that the backups are resilient and restore to the previous datapoint. 
We want to run these tests to find some potential tests early on, and adjust the long running integration tests based on the results

DoD #1. 
Run a successful test scenario where we are able to send multiple transactions from wallet #1 to #2 and back. 

DoD #2 
Restore a node with transaction data when it goes down so we can see if the node keeps the data correctly.

**Comment by marcinwadon** [comment]
DoD 1.

Requirements:
- Create an S3 bucket and provide credentials for cluster
- Spin up a cluster (~20 nodes)
- Spin up a block explorer and connect to the cluster
- Create at least few wallets
- Transfer a particular amount of tokens from nodes to wallets created in the step above
- Confirm that wallet addresses have tokens

Flow 1:
- Create transactions between wallets
- Confirm that wallet addresses have transferred tokens

Flow 2:
- Create one transaction and put it twice to the cluster
- Confirm that destination wallet address received tokens once only
- Confirm that source wallet address has been banned (because of double spend)

Flow 3:
- ?
