### ISSUE TITLE
Redefine when snapshots and snapshot infos should be removed

### ISSUE THREAD

**Issue by marcinwadon** [Constellation-Labs/constellation#857]
To be defined

**Comment by buckysballs** [comment]
The primary goal here is to ensure that Snapshot/SnapshotInfo are not removed until peers no longer need them in the case of the redownload. Given this, Snapshots and SnapshotInfos can be removed at the same time. There is a guarantee that a re-download should occur within the snapshotHeightRedownloadDelayInterval config, however, since nodes can go above snapshotHeightRedownloadDelayInterval and redownload to a lower height, we need to take into account the height above as well. I can think of an edge case for a "double redownload" one from maj height - snapshotHeightRedownloadDelayInterval and one from maj height + snapshotHeightRedownloadDelayInterval. So instead of each node removing snapshots with height (current accepted snapshot height) - 2*snapshotHeightRedownloadDelayInterval, let's just do (current accepted snapshot height) - 3*snapshotHeightRedownloadDelayInterval.

Since we want to wait until we have the condition of a majority snapshot before deleting, let's add a step to persistSnapshot in RedownloadService to make a check for a new majority snapshot at that height and if a new majority is witnessed, delete all Snapshots/SnapshotInfo with heights lower than (current accepted snapshot height) - 3*snapshotHeightRedownloadDelayInterval.

DoD)
- Check for new majority snapshot during persistence and 
- Removal of snaps/snpshotinfo (current accepted snapshot height) - 3*snapshotHeightRedownloadDelayInterval
